# TCL File Generated by Component Editor 10.1sp1
# Thu May 05 14:21:17 CST 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | ltm "LTM controller" v1.0
# | Geng You Chen 2011.05.05.14:21:17
# | This IP can controll LTM on DE2-70 board.
# | 
# | C:/EECS2002/Lab3/ltm.v
# | 
# |    ./ltm.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.1
# | 
package require -exact sopc 10.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module ltm
# | 
set_module_property DESCRIPTION "This IP can controll LTM on DE2-70 board."
set_module_property NAME ltm
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP EECS2002
set_module_property AUTHOR "Geng You Chen"
set_module_property DISPLAY_NAME "LTM controller"
set_module_property TOP_LEVEL_HDL_FILE ltm.v
set_module_property TOP_LEVEL_HDL_MODULE ltm
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file ltm.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s0
# | 
add_interface s0 clock end
set_interface_property s0 clockRate 0

set_interface_property s0 ENABLED true

add_interface_port s0 csi_s0_clk clk Input 1
add_interface_port s0 csi_s0_reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s1
# | 
add_interface s1 avalon end
set_interface_property s1 addressAlignment NATIVE
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock s0
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 isMemoryDevice false
set_interface_property s1 isNonVolatileStorage false
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 printableDevice false
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0

set_interface_property s1 ENABLED true

add_interface_port s1 avs_s1_write_n write_n Input 1
add_interface_port s1 avs_s1_read_n read_n Input 1
add_interface_port s1 avs_s1_writedata writedata Input 2
add_interface_port s1 avs_s1_readdata readdata Output 2
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s2
# | 
add_interface s2 conduit end

set_interface_property s2 ENABLED true

add_interface_port s2 coe_s2_export_NCLK export Output 1
add_interface_port s2 coe_s2_export_GRST export Output 1
add_interface_port s2 coe_s2_export_HD export Output 1
add_interface_port s2 coe_s2_export_VD export Output 1
add_interface_port s2 coe_s2_export_DEN export Output 1
add_interface_port s2 coe_s2_export_R export Output 8
add_interface_port s2 coe_s2_export_G export Output 8
add_interface_port s2 coe_s2_export_B export Output 8
# | 
# +-----------------------------------
